/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator.gui;

import calculator.programmerscalculator.ProgrammerCalculator;
import calculator.scientificcalculator.ScientificCalculator;

/**
 * This class contains all the components of the Graphical user interface.
 * It takes of rendering of the UI and has method that manipulate user data 
 * and gives out the expected result.
 * @version 1.0
 * @author kishore
 */
public class ProgrammerCalculatorPanel extends javax.swing.JPanel {
    //varible to display output on screen.
    private static String choice = "0";
    private static int input1;
    //custom members.
    private static ScientificCalculator scientificCalc = new ScientificCalculator();
    private static ProgrammerCalculator programmerCalc = new ProgrammerCalculator();
     /**
     * Creates new form ProgrammerCalculatorPanal.
     */
    public ProgrammerCalculatorPanel() {
        initComponents();
         scientificCalc.setUp();
         programmerCalc.setUp();
         calculatorDisplay.setText("0");
         binaryOutput.setText("0");
         hexadecimalOutput.setText("0");
         octalOutput.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        calculatorDisplay = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        buttonsPanal = new javax.swing.JPanel();
        cBracketButton = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        revCBracketButton = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        fiveButton = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        rorButton = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        zeroButton = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        sixButton = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        modButton = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        negateButton = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        oneButton = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        equalsButton = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        notButton = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        twoButton = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        rshButton = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lshButton = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        xorButton = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        andButton = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        orButton = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        threeButton = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        fourButton = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        plusButton = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        sevenButton = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        minusButton = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        eightButton = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        divideButton = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        nineButton = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        rolButton = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        backspaceButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        multiplyButton = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        clearButton = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        clearAllButton = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hexadecimalOutput = new javax.swing.JLabel();
        octalOutput = new javax.swing.JLabel();
        binaryOutput = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 720));

        displayPanel.setBackground(new java.awt.Color(255, 255, 255));

        calculatorDisplay.setBackground(new java.awt.Color(255, 255, 255));
        calculatorDisplay.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        calculatorDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculatorDisplay.setText("2455ADF");
        calculatorDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(calculatorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(calculatorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titleLabel.setBackground(new java.awt.Color(255, 204, 204));
        titleLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        titleLabel.setText("Programmer Calculator");

        cBracketButton.setBackground(new java.awt.Color(234, 236, 239));
        cBracketButton.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel53.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("(");
        jLabel53.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout cBracketButtonLayout = new javax.swing.GroupLayout(cBracketButton);
        cBracketButton.setLayout(cBracketButtonLayout);
        cBracketButtonLayout.setHorizontalGroup(
            cBracketButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cBracketButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cBracketButtonLayout.setVerticalGroup(
            cBracketButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cBracketButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        revCBracketButton.setBackground(new java.awt.Color(234, 236, 239));
        revCBracketButton.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel54.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText(")");
        jLabel54.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout revCBracketButtonLayout = new javax.swing.GroupLayout(revCBracketButton);
        revCBracketButton.setLayout(revCBracketButtonLayout);
        revCBracketButtonLayout.setHorizontalGroup(
            revCBracketButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revCBracketButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        revCBracketButtonLayout.setVerticalGroup(
            revCBracketButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revCBracketButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        fiveButton.setBackground(new java.awt.Color(255, 255, 255));
        fiveButton.setPreferredSize(new java.awt.Dimension(80, 80));
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveButtonMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("5");
        jLabel32.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout fiveButtonLayout = new javax.swing.GroupLayout(fiveButton);
        fiveButton.setLayout(fiveButtonLayout);
        fiveButtonLayout.setHorizontalGroup(
            fiveButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fiveButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fiveButtonLayout.setVerticalGroup(
            fiveButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        rorButton.setBackground(new java.awt.Color(234, 236, 239));
        rorButton.setPreferredSize(new java.awt.Dimension(80, 80));
        rorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rorButtonMouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("RoR");
        jLabel43.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout rorButtonLayout = new javax.swing.GroupLayout(rorButton);
        rorButton.setLayout(rorButtonLayout);
        rorButtonLayout.setHorizontalGroup(
            rorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rorButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rorButtonLayout.setVerticalGroup(
            rorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rorButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        zeroButton.setBackground(new java.awt.Color(255, 255, 255));
        zeroButton.setPreferredSize(new java.awt.Dimension(80, 80));
        zeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroButtonMouseClicked(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("0");
        jLabel55.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout zeroButtonLayout = new javax.swing.GroupLayout(zeroButton);
        zeroButton.setLayout(zeroButtonLayout);
        zeroButtonLayout.setHorizontalGroup(
            zeroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zeroButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        zeroButtonLayout.setVerticalGroup(
            zeroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zeroButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sixButton.setBackground(new java.awt.Color(255, 255, 255));
        sixButton.setPreferredSize(new java.awt.Dimension(80, 80));
        sixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixButtonMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("6");
        jLabel33.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout sixButtonLayout = new javax.swing.GroupLayout(sixButton);
        sixButton.setLayout(sixButtonLayout);
        sixButtonLayout.setHorizontalGroup(
            sixButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sixButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sixButtonLayout.setVerticalGroup(
            sixButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        modButton.setBackground(new java.awt.Color(234, 236, 239));
        modButton.setPreferredSize(new java.awt.Dimension(80, 80));
        modButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modButtonMouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Mod");
        jLabel44.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout modButtonLayout = new javax.swing.GroupLayout(modButton);
        modButton.setLayout(modButtonLayout);
        modButtonLayout.setHorizontalGroup(
            modButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        modButtonLayout.setVerticalGroup(
            modButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        negateButton.setBackground(new java.awt.Color(234, 236, 239));
        negateButton.setPreferredSize(new java.awt.Dimension(80, 80));
        negateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negateButtonMouseClicked(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("<html>&plusmn;</html>");
        jLabel56.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout negateButtonLayout = new javax.swing.GroupLayout(negateButton);
        negateButton.setLayout(negateButtonLayout);
        negateButtonLayout.setHorizontalGroup(
            negateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, negateButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        negateButtonLayout.setVerticalGroup(
            negateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(negateButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        oneButton.setBackground(new java.awt.Color(255, 255, 255));
        oneButton.setPreferredSize(new java.awt.Dimension(80, 80));
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneButtonMouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("1");
        jLabel45.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout oneButtonLayout = new javax.swing.GroupLayout(oneButton);
        oneButton.setLayout(oneButtonLayout);
        oneButtonLayout.setHorizontalGroup(
            oneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        oneButtonLayout.setVerticalGroup(
            oneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        equalsButton.setBackground(new java.awt.Color(234, 236, 239));
        equalsButton.setPreferredSize(new java.awt.Dimension(80, 80));
        equalsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsButtonMouseClicked(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("=");
        jLabel57.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout equalsButtonLayout = new javax.swing.GroupLayout(equalsButton);
        equalsButton.setLayout(equalsButtonLayout);
        equalsButtonLayout.setHorizontalGroup(
            equalsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equalsButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        equalsButtonLayout.setVerticalGroup(
            equalsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equalsButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        notButton.setBackground(new java.awt.Color(234, 236, 239));
        notButton.setPreferredSize(new java.awt.Dimension(80, 80));
        notButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notButtonMouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("not");
        jLabel35.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout notButtonLayout = new javax.swing.GroupLayout(notButton);
        notButton.setLayout(notButtonLayout);
        notButtonLayout.setHorizontalGroup(
            notButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        notButtonLayout.setVerticalGroup(
            notButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        twoButton.setBackground(new java.awt.Color(255, 255, 255));
        twoButton.setPreferredSize(new java.awt.Dimension(80, 80));
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoButtonMouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("2");
        jLabel46.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout twoButtonLayout = new javax.swing.GroupLayout(twoButton);
        twoButton.setLayout(twoButtonLayout);
        twoButtonLayout.setHorizontalGroup(
            twoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        twoButtonLayout.setVerticalGroup(
            twoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        rshButton.setBackground(new java.awt.Color(234, 236, 239));
        rshButton.setPreferredSize(new java.awt.Dimension(80, 80));
        rshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rshButtonMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Rsh");
        jLabel25.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout rshButtonLayout = new javax.swing.GroupLayout(rshButton);
        rshButton.setLayout(rshButtonLayout);
        rshButtonLayout.setHorizontalGroup(
            rshButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rshButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rshButtonLayout.setVerticalGroup(
            rshButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rshButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lshButton.setBackground(new java.awt.Color(234, 236, 239));
        lshButton.setPreferredSize(new java.awt.Dimension(80, 80));
        lshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lshButtonMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Lsh");
        jLabel36.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout lshButtonLayout = new javax.swing.GroupLayout(lshButton);
        lshButton.setLayout(lshButtonLayout);
        lshButtonLayout.setHorizontalGroup(
            lshButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lshButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lshButtonLayout.setVerticalGroup(
            lshButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lshButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        xorButton.setBackground(new java.awt.Color(234, 236, 239));
        xorButton.setPreferredSize(new java.awt.Dimension(80, 80));
        xorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xorButtonMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Xor");
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout xorButtonLayout = new javax.swing.GroupLayout(xorButton);
        xorButton.setLayout(xorButtonLayout);
        xorButtonLayout.setHorizontalGroup(
            xorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xorButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        xorButtonLayout.setVerticalGroup(
            xorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xorButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        andButton.setBackground(new java.awt.Color(234, 236, 239));
        andButton.setPreferredSize(new java.awt.Dimension(80, 80));
        andButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                andButtonMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("And");
        jLabel26.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout andButtonLayout = new javax.swing.GroupLayout(andButton);
        andButton.setLayout(andButtonLayout);
        andButtonLayout.setHorizontalGroup(
            andButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, andButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        andButtonLayout.setVerticalGroup(
            andButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(andButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        orButton.setBackground(new java.awt.Color(234, 236, 239));
        orButton.setPreferredSize(new java.awt.Dimension(80, 80));
        orButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orButtonMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Or");
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout orButtonLayout = new javax.swing.GroupLayout(orButton);
        orButton.setLayout(orButtonLayout);
        orButtonLayout.setHorizontalGroup(
            orButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        orButtonLayout.setVerticalGroup(
            orButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        threeButton.setBackground(new java.awt.Color(255, 255, 255));
        threeButton.setPreferredSize(new java.awt.Dimension(80, 80));
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeButtonMouseClicked(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("3");
        jLabel47.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout threeButtonLayout = new javax.swing.GroupLayout(threeButton);
        threeButton.setLayout(threeButtonLayout);
        threeButtonLayout.setHorizontalGroup(
            threeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threeButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        threeButtonLayout.setVerticalGroup(
            threeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threeButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        fourButton.setBackground(new java.awt.Color(255, 255, 255));
        fourButton.setPreferredSize(new java.awt.Dimension(80, 80));
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourButtonMouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("4");
        jLabel37.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout fourButtonLayout = new javax.swing.GroupLayout(fourButton);
        fourButton.setLayout(fourButtonLayout);
        fourButtonLayout.setHorizontalGroup(
            fourButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fourButtonLayout.setVerticalGroup(
            fourButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        plusButton.setBackground(new java.awt.Color(234, 236, 239));
        plusButton.setPreferredSize(new java.awt.Dimension(80, 80));
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusButtonMouseClicked(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("+");
        jLabel48.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout plusButtonLayout = new javax.swing.GroupLayout(plusButton);
        plusButton.setLayout(plusButtonLayout);
        plusButtonLayout.setHorizontalGroup(
            plusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plusButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        plusButtonLayout.setVerticalGroup(
            plusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sevenButton.setBackground(new java.awt.Color(255, 255, 255));
        sevenButton.setPreferredSize(new java.awt.Dimension(80, 80));
        sevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenButtonMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("7");
        jLabel27.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout sevenButtonLayout = new javax.swing.GroupLayout(sevenButton);
        sevenButton.setLayout(sevenButtonLayout);
        sevenButtonLayout.setHorizontalGroup(
            sevenButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sevenButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sevenButtonLayout.setVerticalGroup(
            sevenButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sevenButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        minusButton.setBackground(new java.awt.Color(234, 236, 239));
        minusButton.setPreferredSize(new java.awt.Dimension(80, 80));
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("-");
        jLabel38.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout minusButtonLayout = new javax.swing.GroupLayout(minusButton);
        minusButton.setLayout(minusButtonLayout);
        minusButtonLayout.setHorizontalGroup(
            minusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minusButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        minusButtonLayout.setVerticalGroup(
            minusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minusButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        eightButton.setBackground(new java.awt.Color(255, 255, 255));
        eightButton.setPreferredSize(new java.awt.Dimension(80, 80));
        eightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightButtonMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("8");
        jLabel28.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout eightButtonLayout = new javax.swing.GroupLayout(eightButton);
        eightButton.setLayout(eightButtonLayout);
        eightButtonLayout.setHorizontalGroup(
            eightButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eightButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        eightButtonLayout.setVerticalGroup(
            eightButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eightButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        divideButton.setBackground(new java.awt.Color(234, 236, 239));
        divideButton.setPreferredSize(new java.awt.Dimension(80, 80));
        divideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideButtonMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("<html>&#247;</html>");
        jLabel19.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout divideButtonLayout = new javax.swing.GroupLayout(divideButton);
        divideButton.setLayout(divideButtonLayout);
        divideButtonLayout.setHorizontalGroup(
            divideButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divideButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        divideButtonLayout.setVerticalGroup(
            divideButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divideButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        nineButton.setBackground(new java.awt.Color(255, 255, 255));
        nineButton.setPreferredSize(new java.awt.Dimension(80, 80));
        nineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineButtonMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("9");
        jLabel29.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout nineButtonLayout = new javax.swing.GroupLayout(nineButton);
        nineButton.setLayout(nineButtonLayout);
        nineButtonLayout.setHorizontalGroup(
            nineButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nineButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nineButtonLayout.setVerticalGroup(
            nineButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nineButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        rolButton.setBackground(new java.awt.Color(234, 236, 239));
        rolButton.setPreferredSize(new java.awt.Dimension(80, 80));
        rolButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rolButtonMouseClicked(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("RoL");
        jLabel52.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout rolButtonLayout = new javax.swing.GroupLayout(rolButton);
        rolButton.setLayout(rolButtonLayout);
        rolButtonLayout.setHorizontalGroup(
            rolButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rolButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rolButtonLayout.setVerticalGroup(
            rolButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        backspaceButton.setBackground(new java.awt.Color(234, 236, 239));
        backspaceButton.setPreferredSize(new java.awt.Dimension(80, 80));
        backspaceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspaceButtonMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html>&larr;</html>");
        jLabel20.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout backspaceButtonLayout = new javax.swing.GroupLayout(backspaceButton);
        backspaceButton.setLayout(backspaceButtonLayout);
        backspaceButtonLayout.setHorizontalGroup(
            backspaceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backspaceButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backspaceButtonLayout.setVerticalGroup(
            backspaceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backspaceButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        multiplyButton.setBackground(new java.awt.Color(234, 236, 239));
        multiplyButton.setPreferredSize(new java.awt.Dimension(80, 80));
        multiplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyButtonMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("<html>&#215;</html>");
        jLabel30.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout multiplyButtonLayout = new javax.swing.GroupLayout(multiplyButton);
        multiplyButton.setLayout(multiplyButtonLayout);
        multiplyButtonLayout.setHorizontalGroup(
            multiplyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplyButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        multiplyButtonLayout.setVerticalGroup(
            multiplyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplyButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        clearButton.setBackground(new java.awt.Color(234, 236, 239));
        clearButton.setPreferredSize(new java.awt.Dimension(80, 80));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("C");
        jLabel21.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout clearButtonLayout = new javax.swing.GroupLayout(clearButton);
        clearButton.setLayout(clearButtonLayout);
        clearButtonLayout.setHorizontalGroup(
            clearButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clearButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        clearButtonLayout.setVerticalGroup(
            clearButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        clearAllButton.setBackground(new java.awt.Color(234, 236, 239));
        clearAllButton.setPreferredSize(new java.awt.Dimension(80, 80));
        clearAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearAllButtonMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("AC");
        jLabel22.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout clearAllButtonLayout = new javax.swing.GroupLayout(clearAllButton);
        clearAllButton.setLayout(clearAllButtonLayout);
        clearAllButtonLayout.setHorizontalGroup(
            clearAllButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clearAllButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        clearAllButtonLayout.setVerticalGroup(
            clearAllButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearAllButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Binary");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Hexadecimal");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Octal");

        hexadecimalOutput.setBackground(new java.awt.Color(255, 255, 255));
        hexadecimalOutput.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        hexadecimalOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hexadecimalOutput.setText("0");

        octalOutput.setBackground(new java.awt.Color(255, 255, 255));
        octalOutput.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        octalOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        octalOutput.setText("0");

        binaryOutput.setBackground(new java.awt.Color(255, 255, 255));
        binaryOutput.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        binaryOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        binaryOutput.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hexadecimalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(binaryOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(octalOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(binaryOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hexadecimalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(octalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout buttonsPanalLayout = new javax.swing.GroupLayout(buttonsPanal);
        buttonsPanal.setLayout(buttonsPanalLayout);
        buttonsPanalLayout.setHorizontalGroup(
            buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonsPanalLayout.createSequentialGroup()
                        .addComponent(xorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsPanalLayout.createSequentialGroup()
                        .addComponent(rshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(andButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsPanalLayout.createSequentialGroup()
                        .addComponent(lshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsPanalLayout.createSequentialGroup()
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(buttonsPanalLayout.createSequentialGroup()
                                .addComponent(rorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonsPanalLayout.createSequentialGroup()
                                .addComponent(rolButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revCBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(negateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        buttonsPanalLayout.setVerticalGroup(
            buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanalLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanalLayout.createSequentialGroup()
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(andButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rolButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revCBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonsPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Custom methods.
    private void fiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("5");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "5");
    }//GEN-LAST:event_fiveButtonMouseClicked

    private void rorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rorButtonMouseClicked
        choice = "ror";
    }//GEN-LAST:event_rorButtonMouseClicked

    private void zeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("0");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "0");
    }//GEN-LAST:event_zeroButtonMouseClicked

    private void sixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("6");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "6");
    }//GEN-LAST:event_sixButtonMouseClicked

    private void modButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        calculatorDisplay.setText("");
        choice = "mod";
    }//GEN-LAST:event_modButtonMouseClicked

    private void negateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negateButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        choice = "negate";
    }//GEN-LAST:event_negateButtonMouseClicked

    private void oneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("1");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "1");
    }//GEN-LAST:event_oneButtonMouseClicked

    private void equalsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsButtonMouseClicked
        String outputResult;
        switch(choice) {
            case "mod" : { 
                int input2 = Integer.parseInt(calculatorDisplay.getText());
                outputResult = Integer.toString(input1 % input2);
                break;
            }
            case "negate" : {
                int output = (int)scientificCalc.arihtmeticModule.negate(input1);
                outputResult = Integer.toString(output);
                break;
            }
            case "not" : {
                outputResult = Long.toString(programmerCalc.bitwiseOperation.notOperation(input1));
                break;
            }
            case "rsh" : {
                String input2 = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.rightShiftOperation(input1,Integer.parseInt(input2)));
                break;
            }
            case "lsh" : {
                String input2 = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.leftShiftOperation(input1,Integer.parseInt(input2)));
                break;
            }
            case "xor" : {
                String input2 = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.xorOperation(input1,Integer.parseInt(input2)));
                break;
            }
            case "and" : {
                String input2 = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.andOperation(input1,Integer.parseInt(input2)));
                break;
            }
            case "or" : {
                String input2 = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.orOperation(input1,Integer.parseInt(input2)));
                break;
            }
            case "add" : {
                int input2 = Integer.parseInt(calculatorDisplay.getText());
                outputResult = Long.toString(input1+input2);
                break;
            }
            case "subtract" : {
                int input2 = Integer.parseInt(calculatorDisplay.getText());
                outputResult = Long.toString(input1-input2);
                break;
            }
            case "divide" : {
                int input2 = Integer.parseInt(calculatorDisplay.getText());
                if(input2 !=0)
                    outputResult = Long.toString(input1/input2);
                else
                    outputResult = "0";
                break;
            }
            case "multiply" : {
                int input2 = Integer.parseInt(calculatorDisplay.getText());
                outputResult = Long.toString(input1*input2);
                break;
            }
            case "ror" : {
                String input = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.rightRotateOperation(Integer.parseInt(input)));
                break;
            }
            case "rol" : {
                String input = calculatorDisplay.getText();
                outputResult = Long.toString(programmerCalc.bitwiseOperation.leftRotateOperation(Integer.parseInt(input)));
                break;
            }
            
            default : outputResult =calculatorDisplay.getText();;
        }
        
        calculatorDisplay.setText(outputResult);
        binaryOutput.setText(programmerCalc.decimalInput.convertDecimalToBinary(outputResult));
        hexadecimalOutput.setText(programmerCalc.decimalInput.convertDecimalToHexaDecimal(outputResult));
        octalOutput.setText(programmerCalc.decimalInput.convertDecimalToOctal(outputResult));
    }//GEN-LAST:event_equalsButtonMouseClicked

    private void notButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        choice = "not";
    }//GEN-LAST:event_notButtonMouseClicked

    private void twoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("2");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "2");
    }//GEN-LAST:event_twoButtonMouseClicked

    private void rshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rshButtonMouseClicked
       input1 =Integer.parseInt(calculatorDisplay.getText());
       calculatorDisplay.setText("");
       choice = "rsh";
    }//GEN-LAST:event_rshButtonMouseClicked

    private void lshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lshButtonMouseClicked
       input1 = Integer.parseInt(calculatorDisplay.getText());
       calculatorDisplay.setText("");
       choice = "lsh";
    }//GEN-LAST:event_lshButtonMouseClicked

    private void xorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xorButtonMouseClicked
       input1 = Integer.parseInt(calculatorDisplay.getText());
       calculatorDisplay.setText("");
       choice = "xor"; 
    }//GEN-LAST:event_xorButtonMouseClicked

    private void andButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_andButtonMouseClicked
       input1 = Integer.parseInt(calculatorDisplay.getText());
       calculatorDisplay.setText("");
       choice = "and";
    }//GEN-LAST:event_andButtonMouseClicked

    private void orButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orButtonMouseClicked
       input1 = Integer.parseInt(calculatorDisplay.getText());
       calculatorDisplay.setText("");
       choice = "or";
    }//GEN-LAST:event_orButtonMouseClicked

    private void threeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("3");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "3");
    }//GEN-LAST:event_threeButtonMouseClicked

    private void fourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("4");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "4");
    }//GEN-LAST:event_fourButtonMouseClicked

    private void plusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        calculatorDisplay.setText("");
        choice = "add";
    }//GEN-LAST:event_plusButtonMouseClicked

    private void sevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("7");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "7");
    }//GEN-LAST:event_sevenButtonMouseClicked

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        calculatorDisplay.setText("");
        choice = "subtract";
    }//GEN-LAST:event_minusButtonMouseClicked

    private void eightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("8");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "8");
    }//GEN-LAST:event_eightButtonMouseClicked

    private void divideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        calculatorDisplay.setText("");
        choice = "divide";
    }//GEN-LAST:event_divideButtonMouseClicked

    private void nineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseClicked
        if("0".equals(calculatorDisplay.getText()) || "".equals(calculatorDisplay.getText()))
        calculatorDisplay.setText("9");
        else
        calculatorDisplay.setText( calculatorDisplay.getText() + "9");
    }//GEN-LAST:event_nineButtonMouseClicked

    private void multiplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyButtonMouseClicked
        input1 = Integer.parseInt(calculatorDisplay.getText());
        calculatorDisplay.setText("");
        choice = "multiply";
    }//GEN-LAST:event_multiplyButtonMouseClicked

    private void backspaceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceButtonMouseClicked
        int length = calculatorDisplay.getText().length();
        int number = calculatorDisplay.getText().length()-1;
        if(length > 0) {
            StringBuilder back = new StringBuilder(calculatorDisplay.getText());
            back.deleteCharAt(number);
            String newString = back.toString();
            calculatorDisplay.setText(newString);
            binaryOutput.setText(programmerCalc.decimalInput.convertDecimalToBinary(newString));
            hexadecimalOutput.setText(programmerCalc.decimalInput.convertDecimalToHexaDecimal(newString));
            octalOutput.setText(programmerCalc.decimalInput.convertDecimalToOctal(newString));
        }
    }//GEN-LAST:event_backspaceButtonMouseClicked

    private void clearAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearAllButtonMouseClicked
        scientificCalc.setUp();
        programmerCalc.setUp();
        calculatorDisplay.setText("0");
        binaryOutput.setText("0");
        hexadecimalOutput.setText("0");
        octalOutput.setText("0");
    }//GEN-LAST:event_clearAllButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        calculatorDisplay.setText("0");
        choice = "0";
        binaryOutput.setText("0");
        hexadecimalOutput.setText("0");
        octalOutput.setText("0");
    }//GEN-LAST:event_clearButtonMouseClicked

    private void rolButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolButtonMouseClicked
        choice = "rol";
    }//GEN-LAST:event_rolButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel andButton;
    private javax.swing.JPanel backspaceButton;
    private javax.swing.JLabel binaryOutput;
    private javax.swing.JPanel buttonsPanal;
    private javax.swing.JPanel cBracketButton;
    private javax.swing.JLabel calculatorDisplay;
    private javax.swing.JPanel clearAllButton;
    private javax.swing.JPanel clearButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel divideButton;
    private javax.swing.JPanel eightButton;
    private javax.swing.JPanel equalsButton;
    private javax.swing.JPanel fiveButton;
    private javax.swing.JPanel fourButton;
    private javax.swing.JLabel hexadecimalOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lshButton;
    private javax.swing.JPanel minusButton;
    private javax.swing.JPanel modButton;
    private javax.swing.JPanel multiplyButton;
    private javax.swing.JPanel negateButton;
    private javax.swing.JPanel nineButton;
    private javax.swing.JPanel notButton;
    private javax.swing.JLabel octalOutput;
    private javax.swing.JPanel oneButton;
    private javax.swing.JPanel orButton;
    private javax.swing.JPanel plusButton;
    private javax.swing.JPanel revCBracketButton;
    private javax.swing.JPanel rolButton;
    private javax.swing.JPanel rorButton;
    private javax.swing.JPanel rshButton;
    private javax.swing.JPanel sevenButton;
    private javax.swing.JPanel sixButton;
    private javax.swing.JPanel threeButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel twoButton;
    private javax.swing.JPanel xorButton;
    private javax.swing.JPanel zeroButton;
    // End of variables declaration//GEN-END:variables
}
